AWSTemplateFormatVersion: "2010-09-09"

Resources:
  CognitoUserPoolClient:
    Type: "AWS::Cognito::UserPoolClient"
    Properties:
      UserPoolId: !Ref UserPoolId
      ClientName: "CMSUserPoolClient"
      GenerateSecret: false
      ExplicitAuthFlows:
        - ALLOW_USER_PASSWORD_AUTH
        - ALLOW_REFRESH_TOKEN_AUTH
        - ALLOW_CUSTOM_AUTH
      CallbackURLs:
        - !Ref CallbackURL
      LogoutURLs:
        - !Ref LogoutURL
      SupportedIdentityProviders:
        - COGNITO

Parameters:
  UserPoolId:
    Type: String
    Description: Cognito User Pool ID.

  CallbackURL:
    Type: String
    Description: URL for handling login callback.
    Default: "http://localhost:8000/callback"

  LogoutURL:
    Type: String
    Description: URL for handling logout.
    Default: "http://localhost:8000/logout"
